apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kube-hunter.fullname" . }}
  labels:
    {{- include "kube-hunter.labels" . | nindent 4 }}
spec:
  template:
    metadata:
    {{- with .Values.jobAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "kube-hunter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["kube-hunter"]
        args:
          {{- toYaml .Values.image.args | nindent 12}}
      restartPolicy: Never
  backoffLimit: 4
